#!/bin/bash
[ -z "${CONFIG+x}" ] && CONFIG=$HOME/.pigeos

update() {
  # determinate emulation speed based on the used RasPi
  # Pi 1
  if grep -q "^Revision\s*:\s*00[0-9a-fA-F][0-9a-fA-F]$" /proc/cpuinfo; then
    cpu="80486DX"; speed="20"
  elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]0[0-36][0-9a-fA-F]$" /proc/cpuinfo ; then
    cpu="80486DX"; speed="20"
  # Pi 2
  elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]04[0-9a-fA-F]$" /proc/cpuinfo ; then
    cpu="80486DX"; speed="33"
  # Pi Zero
  elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]0[9cC][0-9a-fA-F]$" /proc/cpuinfo ; then
    cpu="80486DX"; speed="20"
  # Pi Zero 2W
  elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]12[0-9a-fA-F]$" /proc/cpuinfo ; then
    cpu="80486DX"; speed="40"
  # Pi 3
  elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]08[0-9a-fA-F]$" /proc/cpuinfo ; then
    cpu="80486DX2"; speed="50"
  # Pi 3+
  elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]08[0-9a-fA-F]$" /proc/cpuinfo ; then
    cpu="80486DX2"; speed="66"
  # Pi 4
  elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F]03[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$" /proc/cpuinfo ; then
    cpu="80486DX4"
    # check for overclocking as it makes quite a difference in emulation speed
    if [ $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq) -lt 1750000 ]; then
      speed="100"
    else
      speed="133"
    fi
  else
    cpu="UNKNOWN"; speed="??"
  fi
  local mimg="$(basename ${HDC_IMAGE^^} .IMG)"
  local simg="$(basename ${HDD_IMAGE^^} .IMG)"
  local msg="\
Pi/GEOS ${PIGEOS_VER} $(stat --printf='%z' $0 | cut -d ' ' -f1 | date '+%D')\n\
\n\
${cpu}, CPU at ${speed}MHz\n\
Memory Test : 16384K OK\n\
\n\
Raspberry Pi Plug and Play PC/GEOS extension\n\
Copyright \(C\) 2020-22, Thomas Hass\n\
http://www.thobipix.de\n\
\n\
Initialize Plug and Play Options ...\n\
Opt-01: $(lsb_release -ds)\n\
Opt-02: DOSBox version 0.74\n\
PnP init Completed\n\
  Detected HDD Primary Master ... ${mimg:-none}\n\
  Detected HDD Primary Slave  ... ${simg:-none}\n\
\n\
\n\
\n\
\n\
Press Ctrl+F9 to enter SETUP configuration tool\n\
Please wait, Pi/GEOS is booting up ..."

  sudo convert /usr/local/share/pigeos/splash_tpl.png \
   -font Px437-PhoenixEGA-8x16 -pointsize 28 -fill '#e7e7e7' -annotate +33+170 "$msg" \
   -resize ${SCREEN_RESOLUTION%@*} /usr/local/lib/pigeos/splash.png
}
### MAIN ###########################################################################
[ -r ${CONFIG} ] && source $CONFIG
$@
