#!/bin/bash
DOSBOX=/usr/local/bin/dosbox
DOSBOX_USER=$(who | grep tty1 | cut -d\  -f 1)
BT="Pi/GEOS installer v0.1"
LOG_FILE=/tmp/$(basename $0).log
PKG_LIST="iptables ppp socat usbmount timidity-daemon fbi imagemagick jed"
# list of external files used by this script
URL_DOSBOX=""
URL_DIALING_SOUND="https://upload.wikimedia.org/wikipedia/commons/3/33/Dial_up_modem_noises.ogg"
URL_ENSDEMO=""
URL_FONTS="https://int10h.org/oldschool-pc-fonts/download/ultimate_oldschool_pc_font_pack_v1.01.zip"
URL_SPLASH="https://raw.githubusercontent.com/hastho/pigeos/master/gfx/splash_tpl.png"
URL_CONFIG_SCRIPT=""


calc_wt_size() {
  # NOTE: it's tempting to redirect stderr to /dev/null, so supress error
  # output from tput. However in this case, tput detects neither stdout or
  # stderr is a tty and so only gives default 80, 24 values
  WT_HEIGHT=18
  WT_WIDTH=$(tput cols)

  if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
    WT_WIDTH=78
  elif [ "$WT_WIDTH" -gt 178 ]; then
    WT_WIDTH=120
  else
    WT_WIDTH=$(($WT_WIDTH-2))
  fi
  WT_MENU_HEIGHT=$(($WT_HEIGHT-7))
}

say_hello() {
  if (whiptail --backtitle "$BT" --title "Install Pi/GEOS" --yesno "\
This script will install PC/GEOS Ensemble Demo on your\
Raspbian installation. It will add some systems services\
to enable GEOS to dial into the internet.\
Choose Yes to continue or No to abort." $WT_HEIGHT $WT_WIDTH)
  then
    return 0
  else
    whiptail --backtitle "$BT" --title "Install Pi/GEOS" --msgbox "\
Installation abotrted by the user."
    return 1
  fi
}

download_file() {
  wget --progress=dot $1 -O $2 2>&1 \
  | sed -un 's/.* \([0-9]\+\)% .*/\1/p' \
  | whiptail --gauge "Downloading: $1" 7 $WT_WIDTH 0
}

install_pkg() {
  sudo apt-get -y install $*
}

splash_gen()
{
  whiptail --infobox "Creating splash screen image" $WT_HEIGHT $WT_WIDTH
  # determinate emulation speed based on the used RasPi
  # Pi 1
  if grep -q "^Revision\s*:\s*00[0-9a-fA-F][0-9a-fA-F]$" /proc/cpuinfo; then
    cpu="80486DX"; speed="20"
  elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]0[0-36][0-9a-fA-F]$" /proc/cpuinfo ; then
    cpu="80486DX"; speed="20"
  # Pi 2
  elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]04[0-9a-fA-F]$" /proc/cpuinfo ; then
    cpu="80486DX"; speed="33"
  # Pi Zero
  elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]0[9cC][0-9a-fA-F]$" /proc/cpuinfo ; then
    cpu="80486DX"; speed="20"
  # Pi 3
  elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]08[0-9a-fA-F]$" /proc/cpuinfo ; then
    cpu="80486DX2"; speed="50"
  # Pi 3+
  elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]08[0-9a-fA-F]$" /proc/cpuinfo ; then
    cpu="80486DX2"; speed="66"
  # Pi 4
  elif grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]11[0-9a-fA-F]$" /proc/cpuinfo ; then
    cpu="80486DX4"; speed="100"
  else
    cpu="UNKNOWN"; speed="??"
  fi
  local mimg="${1:-None}"
  local simg="${2:-None}"
  local msg="\
PIGEOS ALPHA Rev 0.1 $(date '+%D')\n\
\n\
${cpu}, CPU at ${speed}MHz\n\
Memory Test : 16384K OK\n\
\n\
Raspberry Pi Plug and Play PC/GEOS extension\n\
Copyright \(C\) 2020, Thomas Hass\n\
http://www.thobipix.de\n\
\n\
Initialize Plug and Play Options ...\n\
Opt-01: Raspbian Linux $(cat /etc/debian_version)\n\
Opt-02: DOSBox 0.74 SVN\n\
PnP init Completed\n\
  Detected HDD Primary Master ... ${mimg}\n\
  Detected HDD Primary Slave  ... ${simg}\n\
\n\
\n\
\n\
\n\
Press Ctrl+Alt+F2 to enter SETUP-config\n\
Please wait, Raspbian is being booted ..."

  sudo convert /usr/local/share/pigeos/splash_tpl.png \
   -font Px437-PhoenixEGA-8x16 -pointsize 28 -fill '#e7e7e7' -annotate +33+170 "$msg" \
   /usr/local/lib/pigeos/splash.png
}

install_splash_screen() {
  # This custom splash screen simluates a PC BIOS
  # screen and provides some information about the
  # current Pi/GEOS configuration.
  sudo mkdir -p /usr/local/lib/pigeos 2>&1
  download_file $URL_SPLASH \
    /tmp/splash_tpl.png 2>&1
  sudo mv /tmp/splash_tpl.png  /usr/local/share/pigeos/splash_tpl.png 2>&1
  download_file $URL_FONTS \
    /tmp/ultimate_oldschool_pc_font_pack_v1.01.zip 2>&1
  unzip -jod /tmp /tmp/ultimate_oldschool_pc_font_pack_v1.01.zip '*/Px437_PhoenixEGA_8x16.ttf' 2>&1
  sudo mkdir -p /usr/share/fonts/truetype/oldschool_pc_font 2>&1
  sudo mv /tmp/Px437_PhoenixEGA_8x16.ttf /usr/share/fonts/truetype/oldschool_pc_font 2>&1
  sudo fc-cache -f 2>&1
  splash_gen 2>&1
  whiptail --infobox "Creating splash screen service" $WT_HEIGHT $WT_WIDTH
  sudo tee /etc/systemd/system/splash_screen.service >/dev/null <<SPLASH_SCR
[Unit]
Description=Pi/GEOS splash screen service
DefaultDependencies=no

[Service]
ExecStart=/usr/bin/fbi -noverbose  /usr/local/lib/pigeos/splash.png

StandardInput=tty
StandardOutput=tty


[Install]
WantedBy=multi-user.target
SPLASH_SCR
  # enable service
  sudo systemctl daemon-reload 2>&1
  sudo systemctl enable splash_screen 2>&1
  sudo systemctl start splash_screen 2>&1
  return 0
}

install_dosbox_modem() {
  # DOSBox will foreward it's virtuel modem connection
  # to a local telnet port that will be redirects to
  # a virtuel TTy where a PPPD can bind to
  echo -n "Creating modem service "
  sudo tee /etc/systemd/system/modem@.service >/dev/null <<MODEM_SRV
[Unit]
Description=Start DOSBox virtual modem on given TTY
After=network.target
StartLimitIntervalSec=0
StartLimitBurst=3000

[Service]
Restart=always
RestartSec=3
Type=simple
PIDFile=/run/modem-%i.pid
ExecStart=/usr/bin/socat -L/run/modem-%i.pid -d -d -s -lf /var/log/modem-%i.log TCP4-LISTEN:23,bind=127.0.0.1 PTY,link=/dev/%i,raw,echo=0,b57600 

[Install]
WantedBy=multi-user.target
MODEM_SRV
  echo done.

  # as the virtual TTy is only created by socat when DOSBox
  # establishes a modem connection PPPD service can only
  # be started after the TTY has been created.
  sudo tee /etc/systemd/system/pppd@.path >/dev/null <<PPP_MON
[Unit]
Description=Start PPP, if the given (SoCAT) TTY is present

[Path]
PathExists=/dev/%i

[Install]
WantedBy=multi-user.target
PPP_MON

  # before PPPD will be started a nice modem dialing sound will
  # be played :) At this point NAT will be activated for all
  # interfaces and connection tracking roles to allow active
  # FTP (req. by the GEOS FTP client) are aplied.
  # 
  sudo tee /etc/systemd/system/pppd@.service >/dev/null <<PPP_SRV
[Unit]
Description=Start PPPD for the given TTY

[Service]
Type=simple
EnvironmentFile=/etc/default/pppd-%i.conf
PIDFile=/run/pppd%i.pid
ExecStartPre=-/usr/bin/play /usr/local/share/sound/dialing.ogg
ExecStartPre=/sbin/iptables -t nat -A POSTROUTING -s \$PPPD_NETWORK -j MASQUERADE
ExecStartPre=/sbin/iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
ExecStartPre=/sbin/iptables -A PREROUTING -t raw -p tcp --dport 21 -j CT --helper ftp
ExecStart=/usr/sbin/pppd /dev/%i \$PPPD_CONNECTION \$PPPD_DEFAULTS
PPP_SRV

  # PPPD configuration is different for any serial line and
  # the IP ranges need to be modified. 
  sudo tee /etc/default/pppd-ttyN0.conf >/dev/null <<PPP_CFG
PPPD_DEFAULTS=nodetach local noauth
PPPD_NETWORK=192.168.6.0/30
PPPD_CONNECTION=57600 192.168.6.1:192.168.6.2
PPP_CFG

  # load kernel modules to allow active FTP
  grep -e 'nf_conntrack_ftp|nf_nat_ftp' /etc/modules-load.d/modules.conf \
  || sudo tee -a /etc/modules-load.d/modules.conf >/dev/null <<FTP_MOD
nf_conntrack_ftp
nf_nat_ftp
FTP_MOD

  # enable routing
  sudo tee /etc/sysctl.d/98-ppd.conf >/dev/null <<PPP_SYSCTL
net.ipv4.ip_forward=1
PPP_SYSCTL

  # reload system configuration and enable/start services
  sudo sysctl -p /etc/sysctl.conf
  sudo modprobe nf_nat_ftp
  sudo systemctl daemon-reload
  sudo systemctl enable modem@ttyN0
  sudo systemctl start modem@ttyN0
  sudo systemctl enable pppd@ttyN0.path
  sudo systemctl start pppd@ttyN0.path

  # Configuring DOSBox with modem on COM1
  sed -i 's/serial1 =.*/serial1 = modem listenport:23/' $(dosbox -printconf)
  return 0
}

config_login()
{
  sudo tee /etc/systemd/system/getty@tty1.service.d/autologin.conf >/dev/null <<AUTO_LOGIN
[Service]
ExecStart=
ExecStart=-/sbin/agetty --skip-login --noclear --noissue --login-options "-f pi" %I \$TERM
AUTO_LOGIN  
}

config_usbmount()
{
  # add the pi user to the disk group
  sudo usermod -aG disk $DOSBOX_USER  
  # set mount option to allow write acces
  sudo sed -i 's/^FS_MOUNTOPTIONS=.*/FS_MOUNTOPTIONS="-fstype=vfat,gid=disk,dmask=0007,fmask=0117"/' \
	  /etc/usbmount/usbmount.conf
  # mybe not required, see: https://github.com/rbrito/usbmount/issues/25
  #sudo sed -i 's/MountFlags=slave/MountFlags=shared/g' \
  # 	  /lib/systemd/system/systemd-udevd.service
  # usbmount failed without this setting
  sudo sed -i 's/^PrivateMounts=.*/PrivateMounts=no/' \
          /lib/systemd/system/systemd-udevd.service  
}

config_midi()
{
  # route midi output to timidity
  sed -i 's/midiconfig\s*=.*/midiconfig=128:0/' $($DOSBOX -printconf)
}

enable_ssh()
{
   sudo /usr/bin/raspi-config nonint do_ssh 0
}

config_keyb()
{
  local lang=${1:-de}
  sudo /usr/bin/raspi-config nonint do_configure_keyboard $lang
}

### Main ###
>$LOG_FILE
calc_wt_size
#say_hello 				|| exit 1
#enable_ssh				|| exit 2
#install_pkg $PKG_LIST >>$LOG_FILE 2>&1 	|| exit 3
#install_splash_screen
#install_dosbox_modem                    || exit 4
config_usbmount				|| exit 5
#config_keyb				|| exit 6
#config_midi				|| exit 7

rm $LOG_FILE

