#!/bin/bash
#set -x
#set -e
# second stage installation
source /usr/local/etc/pigeos.conf
# finish pending setup stages
if [ $CONTINUE_SETUP -ne 0 ]; then
  pigeos-setup install_stage${CONTINUE_SETUP}
fi
# when exec this script from the profile no keyboard is available
# therefore DOSBox & pigeos-config are running in an endless loop
# until pigeos-config returns a non zero exit code (e.g. DEBUG=1)
while :; do
  source $HOME/.pigeos
  # check for min configuration
  if [ -x ${DOSBOX_BIN} -a -w ${HDC_IMAGE} ] ; then
    # create a session configuration 
    session_conf=`dirname $($DOSBOX_BIN -printconf)`/dosbox-session.conf
	echo "[autoexec]" >${session_conf}
	if   [ -f ${HDC_IMAGE} ] ; then
	  echo "imgmount c ${HDC_IMAGE} -t hdd" >>${session_conf}
	elif [ -d ${HDC_IMAGE} ] ; then
	  echo "mount c ${HDC_IMAGE}" 			>>${session_conf}
	fi
    # mount other drives when an image present 
    if   [ -w ${FDA_IMAGE} -a -f ${FDA_IMAGE} ] ; then
      echo "imgmount a ${HDD_IMAGE} -t floppy" >>${session_conf}
    fi
    if   [ -w ${FDB_IMAGE} -a -f ${FDB_IMAGE} ] ; then
      echo "imgmount b ${HDD_IMAGE} -t floppy" >>${session_conf}
    fi
	if   [ -w ${HDD_IMAGE} -a -f ${HDD_IMAGE} ] ; then
      echo "imgmount d ${HDD_IMAGE} -t hdd" >>${session_conf}
	elif [ -w ${HDD_IMAGE} -a -d ${HDD_IMAGE} ] ; then
	  echo "mount d ${HDD_IMAGE}"			>>${session_conf}
	fi
	if [ ${RSLSYNC_SLOAD} -eq 1 -a -d "$HOME/Shared" ] ; then
      echo "mount s $HOME/Shared" >>${session_conf}
	fi
    if [ ${MOUNT_USB} -eq 1 -a -w /media/usb ] ; then
      echo "mount u /media/usb" >>${session_conf}
	fi
	echo "keyb ${KEYB:-us} 850" >>${session_conf}
	echo "call c:\autoexec.bat" >>${session_conf}
	# restore volume level
	amixer -q -M sset PCM "${VOL_LEVEL:=80}%" 1>/dev/null 2>&1
	# detect if X11 is allready running or not and launch DOSBox
	if xset q >/dev/null 2>&1 ; then
	  $DOSBOX_BIN -userconf -conf ${session_conf}
	else
  	  startx $DOSBOX_BIN -userconf -conf ${session_conf} -- \
	    -dpms -quiet 1>>/tmp/pigeos-loader.log 2>&1
	fi
  fi
  # run SETUP-config if something went wrong
  pigeos-config
  [ $? -ne 0 ] && break
done
  
