#!/bin/bash
# Pi/GEOS installer v0.1"
set -e
set -x
# essential raspi configuration files
BOOT_CONFIG=/boot/config.txt
BOOT_CMDLINE=/boot/cmdline.txt
# base for Pi/GEOS system files and binaries
PIGEOS_PREFIX=/usr/local
# which dosbox binary should be launched?
DOSBOX_BIN=$PIGEOS_PREFIX/bin/dosbox
DOSBOX_USER=$(who | grep tty1 | cut -d\  -f 1)
# packages Pi/GEOS and dosbox-pigeos depend on:
PKG_LIST="iptables ppp socat usbmount timidity-daemon fbi imagemagick jed pv"
# list of external files need to be installed by this script
# a customized version of DOSBox
URL_DOSBOX_PKG="https://dl.dropbox.com/s/8s7ge2co2qmw1q6/dosbox_0.74%2Bpigeos_armhf.deb"
# a classic modem style dialing sound
URL_DIALING_SOUND="https://upload.wikimedia.org/wikipedia/commons/3/33/Dial_up_modem_noises.ogg"
# a font to be used in the BIOS splash screen and splash screen template
URL_FONTS="https://int10h.org/oldschool-pc-fonts/download/ultimate_oldschool_pc_font_pack_v1.01.zip"
URL_SPLASH="https://raw.githubusercontent.com/hastho/pigeos/master/gfx/splash_tpl.png"
# the DOSBox launcher
URL_LOADER="https://raw.githubusercontent.com/hastho/pigeos/master/pigeos-loader"
# Pi/GEOS configuration script, fixed values configuration file and language files
URL_CONFIG_SCRIPT="https://raw.githubusercontent.com/hastho/pigeos/master/pigeos-config"
URL_CONFIG_SYSCFG="https://raw.githubusercontent.com/hastho/pigeos/master/defaults/pigeos.conf"
URL_CONFIG_LANG=(\
  "https://raw.githubusercontent.com/hastho/pigeos/master/pigeos-config.de_DE.UTF-8" \
  "https://raw.githubusercontent.com/hastho/pigeos/master/pigeos-config.en_US.UTF-8" \
)

LOG_FILE=/tmp/$(basename $0).log

download_file() {
  wget -q i"$1" -O "$2" 
}

install_dep_pkg() {
  sudo apt-get -y install $*
}

install_dosbox_pkg() {
  download_file "$URL_DOSBOX_PKG" /tmp/dosbox.deb
  sudo dpkg -i /tmp/dosbox.deb
}

install_pigeos_loader() {
  download_file "$URL_LOADER" /tmp/$(basename "$URL_LOADER")
  sudo install /tmp/$(basename "$URL_LOADER") $PIGEOS_PREFIX/bin
}

install_pigeos_config() {
  download_file "$URL_CONFIG_SCRIPT" /tmp/$(basename "$URL_CONFIG_SCRIPT")
  sudo install /tmp/$(basename "$URL_CONFIG_SCRIPT") $PIGEOS_PREFIX/bin
  download_file "$URL_CONFIG_SYSCFG" /tmp/$(basename "$URL_CONFIG_SYSCFG")
  sudo install /tmp/$(basename "$URL_CONFIG_SYSCFG") $PIGEOS_PREFIX/etc
  for lang in ${URL_CONFIG_LANG[@]}; do
    download_file "$lang" /tmp/$(basename "$lang")
	sudo install /tmp/$(basename "$lang") $PIGEOS_PREFIX/share/pigeos
  done
}

install_splash_screen() {
  # This custom splash screen simluates a PC BIOS
  # screen and provides some information about the
  # current Pi/GEOS configuration.
  download_file $URL_SPLASH \
    /tmp/splash_tpl.png 2>&1
  sudo install /tmp/splash_tpl.png  \
    $PIGEOS_REFIX/share/pigeos 2>&1
  download_file $URL_FONTS \
    /tmp/ultimate_oldschool_pc_font_pack.zip 2>&1
  unzip -jod /tmp /tmp/ultimate_oldschool_pc_font_pack.zip \
    '*/Px437_PhoenixEGA_8x16.ttf' 2>&1 
  sudo install /tmp/Px437_PhoenixEGA_8x16.ttf \
    /usr/share/fonts/truetype/oldschool_pc_font 2>&1
  sudo fc-cache -f 2>&1
  # create image config params req. by pigeos-splash, if not present
  for param in FDA_IMAGE FDB_IMAGE HDC_IMAGE HDD_IMAGE; do
    grep "${param}=.*" $HOME/.pigeos || echo "${param}=NONE" >> $HOME/.pigeos
  done
  pigeos-splash update 2>&1
  echo "Creating splash screen service" 
  sudo tee /etc/systemd/system/splash_screen.service >/dev/null <<SPLASH_SCR
[Unit]
Description=Pi/GEOS splash screen service
DefaultDependencies=no

[Service]
ExecStart=/usr/bin/fbi -noverbose  /usr/local/lib/pigeos/splash.png

StandardInput=tty
StandardOutput=tty


[Install]
WantedBy=multi-user.target
SPLASH_SCR
  # enable service
  sudo systemctl daemon-reload 2>&1
  sudo systemctl enable splash_screen 2>&1
  sudo systemctl start splash_screen 2>&1
  return 0
}

install_dosbox_modem() {
  # DOSBox will foreward it's virtuel modem connection
  # to a local telnet port that will be redirects to
  # a virtuel TTy where a PPPD can bind to
  echo -n "Creating modem service "
  sudo tee /etc/systemd/system/modem@.service >/dev/null <<MODEM_SRV
[Unit]
Description=Start DOSBox virtual modem on given TTY
After=network.target
StartLimitIntervalSec=0
StartLimitBurst=3000

[Service]
Restart=always
RestartSec=3
Type=simple
PIDFile=/run/modem-%i.pid
ExecStart=/usr/bin/socat -L/run/modem-%i.pid -d -d -s -lf /var/log/modem-%i.log TCP4-LISTEN:23,bind=127.0.0.1 PTY,link=/dev/%i,raw,echo=0,b57600 

[Install]
WantedBy=multi-user.target
MODEM_SRV
  echo done.

  # as the virtual TTy is only created by socat when DOSBox
  # establishes a modem connection PPPD service can only
  # be started after the TTY has been created.
  sudo tee /etc/systemd/system/pppd@.path >/dev/null <<PPP_MON
[Unit]
Description=Start PPP, if the given (SoCAT) TTY is present

[Path]
PathExists=/dev/%i

[Install]
WantedBy=multi-user.target
PPP_MON

  # before PPPD will be started a nice modem dialing sound will
  # be played :) At this point NAT will be activated for all
  # interfaces and connection tracking roles to allow active
  # FTP (req. by the GEOS FTP client) are aplied.
  # 
  sudo tee /etc/systemd/system/pppd@.service >/dev/null <<PPP_SRV
[Unit]
Description=Start PPPD for the given TTY

[Service]
Type=simple
EnvironmentFile=/etc/default/pppd-%i.conf
PIDFile=/run/pppd%i.pid
ExecStartPre=-/usr/bin/play /usr/local/share/sound/dialing.ogg
ExecStartPre=/sbin/iptables -t nat -A POSTROUTING -s \$PPPD_NETWORK -j MASQUERADE
ExecStartPre=/sbin/iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
ExecStartPre=/sbin/iptables -A PREROUTING -t raw -p tcp --dport 21 -j CT --helper ftp
ExecStart=/usr/sbin/pppd /dev/%i \$PPPD_CONNECTION \$PPPD_DEFAULTS
PPP_SRV

  # PPPD configuration is different for any serial line and
  # the IP ranges need to be modified. 
  sudo tee /etc/default/pppd-ttyN0.conf >/dev/null <<PPP_CFG
PPPD_DEFAULTS=nodetach local noauth
PPPD_NETWORK=192.168.6.0/30
PPPD_CONNECTION=57600 192.168.6.1:192.168.6.2
PPP_CFG

  # load kernel modules to allow active FTP
  grep -e 'nf_conntrack_ftp|nf_nat_ftp' /etc/modules-load.d/modules.conf \
  || sudo tee -a /etc/modules-load.d/modules.conf >/dev/null <<FTP_MOD
nf_conntrack_ftp
nf_nat_ftp
FTP_MOD

  # enable routing
  sudo tee /etc/sysctl.d/98-ppd.conf >/dev/null <<PPP_SYSCTL
net.ipv4.ip_forward=1
PPP_SYSCTL

  # reload system configuration and enable/start services
  sudo sysctl -p /etc/sysctl.conf
  sudo modprobe nf_nat_ftp
  sudo systemctl daemon-reload
  sudo systemctl enable modem@ttyN0
  sudo systemctl start modem@ttyN0
  sudo systemctl enable pppd@ttyN0.path
  sudo systemctl start pppd@ttyN0.path

  # Configuring DOSBox with modem on COM1
  sed -i 's/serial1=.*/serial1=modem listenport:23/' $(dosbox -printconf)
  return 0
}

config_login()
{
  # raspi-config will switch to text console mode and 
  # enables auto-login  on TTY1 for the user who 
  # executes this script
  sudo /usr/bin/raspi-config nonint do_boot_behaviour B2
  # to make the login realy "silent" so that no output apears between the BIOS splash 
  # and theDOSBox splash the autologin.conf file needs to be modified
  sudo tee /etc/systemd/system/getty@tty1.service.d/autologin.conf >/dev/null <<LOGIN_AUTO
[Service]
ExecStart=
ExecStart=-/sbin/agetty --noissue --skip-login --login-program /bin/login --login-options '-f pi'  %I \$TERM
LOGIN_AUTO
  # also remove the "last login" message
  sudo sed -i 's/^LASTLOG_ENAB/#LASTLOG_ENAB/' /etc/login.defs
  # create a login profile setting to exec the Pi/GEOS loader after login
  sudo tee /etc/profile.d/10-pigeos.sh >/dev/null <<LOGIN_PROF
if [ "\$(tty)" = "/dev/tty1" ]; then
  $PIGEOS_LOADER
fi
LOGIN_PROF
}

config_usbmount()
{
  # add the pi user to the disk group
  sudo usermod -aG disk $DOSBOX_USER  
  # set mount option to allow write acces
  sudo sed -i 's/^FS_MOUNTOPTIONS=.*/FS_MOUNTOPTIONS="-fstype=vfat,gid=disk,dmask=0007,fmask=0117"/' \
	  /etc/usbmount/usbmount.conf
  # usbmount failed without this setting
  sudo mkdir -p /etc/systemd/system/systemd-udevd.service.d
  sudo tee /etc/systemd/system/systemd-udevd.service.d/override.conf >/dev/null <<PRIV_MNT
[Service]
PrivateMounts=no
PRIV_MNT
}

config_midi()
{
  # route midi output to timidity
  sed -i 's/midiconfig\s*=.*/midiconfig=128:0/' $($DOSBOX_BIN -printconf)
}

enable_ssh()
{
   sudo /usr/bin/raspi-config nonint do_ssh 0
}

config_keyb()
{
  local lang=${1:-de}
  sudo /usr/bin/raspi-config nonint do_configure_keyboard $lang
}

config_boot()
{
  # don't wait for the network
  sudo /usr/bin/raspi-config nonint do_boot_wait 1
  # TODO remove DBUS sub-system?
}

config_jed() {
  cat >/HOME/$DOSBOX_USER/.jedrc <<JEDRC
() = evalfile ("cua");
set_color_scheme ("blue3");
TAB_DEFAULT = 4;
JEDRC
}

### Main ###
>$LOG_FILE
install_dep_pkg $PKG_LIST 	|| exit 1
install_dosbox_pkg      || exit 2
install_pigeos_loader   || exit 3
install_pigeos_config   || exit 4
install_splash_screen   || exit 5
install_dosbox_modem    || exit 6

config_login            || exit 7
# TODO use pigeos-config advanced menu
config_usbmount     	|| exit 8
# TODO use pigeos-config basic menu
config_keyb	        	|| exit 9
# TODO use pigeos-config advanced menu
config_midi		        || exit 10
config_jed              || exit 11
# TODO use pigeos-config advanced menu
enable_ssh		        || exit 12
#
cat $LOG_FILE
echo "Press Enter to finish"; read
rm $LOG_FILE



